### ISSUE TITLE
Develop Home screen

### ISSUE THREAD

**Issue by cybunayog** [cybunayog/weathering-app#4]
- Use `useEffect()` to call the weather api so it will update when mounted on the screen (meaning it will update when you're on the home screen
- Have the home screen render the current phone's location weather (can be done by calling `useCurrentWeather()`
- Display:
   - temp
   - weather
   - city/location
   - 3 day forecast (calling `useForecast()`)

**Comment by tgrozenski** [comment]
Hey Cy, 

I have somewhat of a rough working start for the App.tsx file, I wasn't able to get the useCurrentWeather() and useForecast() api calls to work locally so I did my best to infer what the api response would look like based on the example responses on the openweather website. Here is what I have so far: 
```export default function App() {
  
  var { location } = useLocation();
  var { currentWeatherData, loadingCurrentWeatherData, currentWeatherError } =
    getCurrentWeather(
      location?.coords.latitude || 0,
      location?.coords.longitude || 0,
    );
  var  { forecast }  = useForecast();
  
  
  useEffect(() => {

   updateWeather();
    
  },[]);
  
  const updateWeather = () => {
    location  = useLocation();
    currentWeatherData = 
    getCurrentWeather( 
    location?.coords.latitude || 0,
    location?.coords.longitude || 0);
    forecast = useForecast();
  }

  return (
    <View style={styles.container}>
      {loadingCurrentWeatherData ? <Text>Loading...</Text> : <></>}
      <View style={ styles.temp }>
        {currentWeatherData ? <Text>{currentWeatherData.current.temp}</Text> : <></>}
      </View>
      {currentWeatherData ? <Text>{currentWeatherData.current.weather.main}</Text> : <></>}
      {currentWeatherData ? <Text>{currentWeatherData.current.weather.description}</Text> : <></>}
      {location ? <Text> { location } </Text>: <></>}
      <ScrollView>
      {forecast ? <Text>{forecast.day1}</Text> : <></>}
      {forecast ? <Text>{forecast.day2}</Text> : <></>}
      {forecast ? <Text>{forecast.day3}</Text> : <></>}
      </ScrollView>
      {currentWeatherData ? <Text>{currentWeatherData.name}</Text> : <></>}
      {currentWeatherError ? (
        <Text>Error: {currentWeatherError.message}</Text>
      ) : (
        <></>
      )}
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  temp: {
    justifyContent:'flex-end',
    flexDirection:'row',
    flex:1
  }
});```

**Comment by cybunayog** [comment]
@tgrozenski  oh yeah, you can actually create a working branch from `main` to save your changes and not affect `main`'s workflow by doing this:
```
// on main branch
git checkout -b feature/develop-home-screen

// push local branch (even after making commits) into the remote repo
git push feature/develop-home-screen
```

it'll be easier for me to check your code out as a [Pull Request](https://github.com/cybunayog/weathering-app/pulls) and I can make the necessary comments for your learning.

**Comment by tgrozenski** [comment]
ok makes sense ill get on that rn

**Comment by cybunayog** [comment]
also, `useLocation()` and `useForecast()` are hooks which can't go inside of a `useEffect()` based on the [react rules of hooks](https://legacy.reactjs.org/docs/hooks-rules.html). because those hooks are already being updated from `useOpenWeatherApi()`, i think you can just grab the variables from the hook it returns. a good example of that would be `getCurrentWeather()`

**Comment by cybunayog** [comment]
@tgrozenski i totally forgot to note that you should clone the repo before creating a new branch, my bad haha

```git clone https://github.com/cybunayog/weathering-app.git```

**Comment by tgrozenski** [comment]
thanks for explaining and providing the link, I didn't understand what was going on because I did not understand the concept of custom hooks. What will the difference in return values be between useCurrentWeather, getCurrentWeather, and useOpenWeatherApi?

**Comment by cybunayog** [comment]
`useOpenWeatherApi` returns the results from the third party API we're trying to get weather & forecast data from. `useCurrentWeather` doesn't exist, but `getCurrentWeather` would return this:
```{
  "coord": {
    "lon": 10.99,
    "lat": 44.34
  },
  "weather": [
    {
      "id": 501,
      "main": "Rain",
      "description": "moderate rain",
      "icon": "10d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 298.48,
    "feels_like": 298.74,
    "temp_min": 297.56,
    "temp_max": 300.05,
    "pressure": 1015,
    "humidity": 64,
    "sea_level": 1015,
    "grnd_level": 933
  },
  "visibility": 10000,
  "wind": {
    "speed": 0.62,
    "deg": 349,
    "gust": 1.18
  },
  "rain": {
    "1h": 3.16
  },
  "clouds": {
    "all": 100
  },
  "dt": 1661870592,
  "sys": {
    "type": 2,
    "id": 2075663,
    "country": "IT",
    "sunrise": 1661834187,
    "sunset": 1661882248
  },
  "timezone": 7200,
  "id": 3163858,
  "name": "Zocca",
  "cod": 200
} 
```

This can be accessed when using:
```
const { currentWeatherData, loadingCurrentWeatherData, currentWeatherError } =
    getCurrentWeather(
      location?.coords.latitude || 0,
      location?.coords.longitude || 0,
    );

// currentWeatherData will return that object
// how to access the returned data:
const weather = currentWeatherData[0].weather; // returns "Rain"
const weatherDescription = currentWeatherData[0].description; // returns "moderate rain"
const visibility = currentWeatherData.visibility; // returns 10000
const {lat, lon} = currentWeatherData.coords; // returns {lat: 44.34, lon: 10.99}
```

**Comment by cybunayog** [comment]
More info about OpenWeather's API response on the weather object here: https://openweathermap.org/current

Forecast:
https://openweathermap.org/forecast5

**Comment by cybunayog** [comment]
@tgrozenski for the home screen (since we don't have a set design yet) try to render the following as `<Text>`:
- Current user's location (from getCurrentWeather)
   - Display city and country 
- current weather
- current weather description
- current temperature
- current time

**Comment by tgrozenski** [comment]
Ok thanks for the info it makes a lot more sense now! Ill apply the changes and send a pull request in a bit.
